"""change age1

Revision ID: b3e1803fb393
Revises: 
Create Date: 2023-02-03 17:25:56.396655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3e1803fb393'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Book',
    sa.Column('B_ID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('Book_Name', sa.String(length=40), nullable=False),
    sa.Column('Author', sa.String(length=30), nullable=True),
    sa.Column('Pub_Year', sa.Integer(), nullable=True),
    sa.Column('Pub_Name', sa.String(length=30), nullable=True),
    sa.Column('Rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('B_ID')
    )
    op.create_table('Documentary',
    sa.Column('D_ID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('Doc_Name', sa.String(length=40), nullable=False),
    sa.Column('Director', sa.String(length=30), nullable=True),
    sa.Column('Release_date', sa.Date(), nullable=True),
    sa.Column('Rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('D_ID')
    )
    op.create_table('Movie',
    sa.Column('M_ID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('Mov_Name', sa.String(length=40), nullable=False),
    sa.Column('Director', sa.String(length=30), nullable=True),
    sa.Column('Mov_date', sa.Date(), nullable=True),
    sa.Column('Rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('M_ID')
    )
    op.create_table('User',
    sa.Column('Fname', sa.String(length=20), nullable=False),
    sa.Column('Lname', sa.String(length=20), nullable=True),
    sa.Column('Email_ID', sa.String(length=40), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=False),
    sa.Column('Country', sa.String(length=15), server_default='India', nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('psw', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('Email_ID')
    )
    op.create_table('Reviews',
    sa.Column('Review_ID', sa.Integer(), nullable=False),
    sa.Column('Rev_Title', sa.String(length=30), nullable=True),
    sa.Column('Rev_date', sa.Date(), nullable=True),
    sa.Column('Movie_ID', sa.Integer(), nullable=True),
    sa.Column('Doc_ID', sa.Integer(), nullable=True),
    sa.Column('Book_ID', sa.Integer(), nullable=True),
    sa.Column('Username', sa.String(length=20), nullable=True),
    sa.Column('content', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['Book_ID'], ['Book.B_ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Doc_ID'], ['Documentary.D_ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Movie_ID'], ['Movie.M_ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Username'], ['User.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Review_ID')
    )
    op.drop_table('reviews')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('Email_ID')

    op.drop_table('user')
    op.drop_table('documentary')
    op.drop_table('movie')
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('B_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Book_Name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('Author', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Pub_Year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Pub_Name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('B_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('movie',
    sa.Column('M_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Mov_Name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('Director', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Mov_date', sa.DATE(), nullable=True),
    sa.Column('Rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('M_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('documentary',
    sa.Column('D_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Doc_Name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('Director', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Release_date', sa.DATE(), nullable=True),
    sa.Column('Rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('D_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('Fname', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Lname', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Email_ID', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('Age', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Country', mysql.VARCHAR(length=15), server_default=sa.text("'India'"), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('psw', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('Email_ID', ['Email_ID'], unique=False)

    op.create_table('reviews',
    sa.Column('Review_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Rev_Title', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Rev_date', sa.DATE(), nullable=True),
    sa.Column('Movie_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Doc_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Book_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Username', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['Book_ID'], ['book.B_ID'], name='reviews_ibfk_3', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Doc_ID'], ['documentary.D_ID'], name='reviews_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Movie_ID'], ['movie.M_ID'], name='reviews_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Username'], ['user.username'], name='reviews_ibfk_4', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Review_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Reviews')
    op.drop_table('User')
    op.drop_table('Movie')
    op.drop_table('Documentary')
    op.drop_table('Book')
    # ### end Alembic commands ###
